### ISSUE TITLE
Head 2 neckline normals

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/rust-issues#17]

**Comment by garrynewman** [comment]
Any chance of getting a fix for this today?

**Comment by trwb** [comment]
Yeah sure thing. I'll just recheck to see if everything works. I know there's a skinning issue with head2 with the mouth that needs to be fixed.

**Comment by garrynewman** [comment]
Here's a picture of the problem

![image](https://cloud.githubusercontent.com/assets/928843/6605643/689c82f0-c829-11e4-8710-142da2e286f3.png)

**Comment by trwb** [comment]
Is that with the old torso?

**Comment by garrynewman** [comment]
Yeah. I had to roll back your commit yesterday because you made all of the skin prefabs empty files and changed the ids in their meta files. I tried to reapply your model changes but they didn't seem to work.

**Comment by trwb** [comment]
Oh dang it :O
