### ISSUE TITLE
Upgrade to Armoured door takes double Metal Frags

### ISSUE THREAD

**Issue by Holmzy** [Facepunch/rust-issues#22]
When upgrading a door to armor (from default) with a metal stack of 176, it uses all 176 from that stack, rather than just the 100 needed. When upgrading a door with one stack of 101 metal and a second stack of 1 metal, both stacks are completely used. Similarly, there are two separate "-100 metal" boxes that popup on the right side of the screen.

**Comment by garrynewman** [comment]
Fixed
