### ISSUE TITLE
Too difficult to hear people running up behind you

### ISSUE THREAD

**Issue by thebadaids** [Facepunch/rust-issues#24]
At the moment other peoples footsteps are near silent even when they are running. 
I am all for people sneaking up, but they should need to crouch when sneaking at least.

**Comment by y0himba** [comment]
I agree with this.  There should be a ramping up of sound as they get closer if they are running...I.e. the close they get, the louder the sound.  If they are sneaking, when they get really close, there should be a slight rustling noise.

**Comment by arehberg** [comment]
Just did a rough tuning pass with the falloff curves. Should be a hell of a lot better on dev now :)
