### ISSUE TITLE
Remove SHIFT+P and +L

### ISSUE THREAD

**Issue by SannyOK** [Facepunch/rust-issues#25]
Remove it from moderators... They no need to use this, becuase they MODS. Only for ADMins nee to be this...

**Comment by SannyOK** [comment]
Remove it from moderators... They no need to use this, becuase they MODS. Only for ADMins nee to be this...

**Comment by y0himba** [comment]
This is part of why Facepunch will not open these venues to public comment. Moderators DO absolutely need these features, as they are there to admin the server in my (the server owner's) absence. These were tools added to help.

**Comment by offemnow** [comment]
don't think this is a suggestion box, this is a place to post glitches and bugs I believe.

**Comment by y0himba** [comment]
I think suggestions are welcome as well, but you are correct, the blog says "issues".   The blog also says public comments are not accepted, they always turn to "shit".  Lets try and prevent that this time, shall we?
