### ISSUE TITLE
Cave buildings dont take damage/sleepers in caves cant be killed

### ISSUE THREAD

**Issue by offemnow** [Facepunch/rust-issues#28]
So this issue has been around a few weeks but I figured I would post it here anyways, cave bases only take damage from c4 and you cant kill a player in a cave with anything and same with their sleeper. I have closed off all caves on my server till this gets fixed.

**Comment by y0himba** [comment]
This has been around since caves were introduced.  It was fixed for a couple of updates, but then reintroduced. Sleepers and players can be killed by placing a campfire on them. Hit boxes are off, but they are there. 

This already has a bug open at http://support.facepunchstudios.com
