### ISSUE TITLE
Texture tearing near waters edge

### ISSUE THREAD

**Issue by DerangedChicken** [Facepunch/rust-issues#29]
Not sure if anyone else had this but any rocks, buildings or plants in hge water or right on the edge have a strange tearingneffect. As I run black rips form along the edge of whatever object but when I stand still it looks mostly fine, wasn't happening a week ago when I tried rust.

**Comment by y0himba** [comment]
I can confirm this.  I have dual ATI Radeon HD 7950 cards.  Graphic setting are Fantastic, FOV 85, Graphics quality 5, Terrain 100, Water reflections 2, Draw distance 5,000, Motion blur off, AO on, AA on, Lens dirt off, Sun shafts on, Colour grading on PVT on
