### ISSUE TITLE
Lanterns, Campfires and Furnaces have no sounds + render distance problem

### ISSUE THREAD

**Issue by DeathbyStorm28** [Facepunch/rust-issues#31]
As what the title says, the lanterns, campfires and furnaces have no sounds and as for the render distance, at max render distance I can see through people's bases/walls  if I stand far enough (because they haven't rendered yet I'm assuming) and thus I know which walls to break.

**Comment by arehberg** [comment]
The missing sounds should be fixed on dev already :)
