### ISSUE TITLE
Unable to run on dedicated GPU

### ISSUE THREAD

**Issue by anthok** [Facepunch/rust-issues#32]
It doesn't matter if you set your dedicated GPU to run Rust in the NVIDIA control panel. Rust will automatically run on the integrated GPU.

![rust](https://cloud.githubusercontent.com/assets/3751124/6649893/07ab3094-c9ce-11e4-8114-cb3a5e23d14f.png)

Windows 8.1
NVIDIA GTX 780M

**Comment by garrynewman** [comment]
Unfortunately this is an issue with your hardware, or with Windows. You might have an option to turn power saving mode off which will force it to use your dedicated gpu instead.
