### ISSUE TITLE
Low walls not lining up with pillars well

### ISSUE THREAD

**Issue by arehberg** [Facepunch/rust-issues#33]
I haven't checked if this is only on the wood tier, but this looks a little janky

![screen shot 2015-03-13 at 10 40 17 am](https://cloud.githubusercontent.com/assets/1221545/6649996/00099322-c9b9-11e4-8fa4-b81e557b10d3.png)

**Comment by paroxum** [comment]
Now the twig and wood low walls detect if there is a pillar or a wall adjascent.

![wall low fixed](https://cloud.githubusercontent.com/assets/11387355/6651582/d30d2ec4-ca3f-11e4-9bb8-c88a0d0198a6.JPG)
