### ISSUE TITLE
Seeing through floor

### ISSUE THREAD

**Issue by funjoker** [Facepunch/rust-issues#38]
If you jump on a furnace or other tall stuff in a house and stand up youa re abelt to look trough the floor and interact with stuff there.

**Comment by ix1805** [comment]
Had a similar issue where we could see through the top of a floor block, but couldn't see through the bottom of the block, even after rejoining the server later in the day or later in the week that same floor block would consistently be bugged.

**Comment by Helkus** [comment]
Fixed this when I fixed uncrouching
