### ISSUE TITLE
Foundation collision meshes

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/rust-issues#44]
Collision meshes for the few different tiers of foundation meshes where the current cube doesn't work. Basically anything with the pile style legs.

For technical reasons this needs to be pivoted in the right place and needs to be a single mesh.

**Comment by garrynewman** [comment]
If you make the meshes, I'll write the code so that different grades will use the right meshes, so people will be able to walk under stilted buildings.

**Comment by paroxum** [comment]
Yeah I can make the meshes sometime middle of this week ;-)

**Comment by paroxum** [comment]
So the collision meshes have been in this morning, can be found in their respective Parts folders along side the other fbx's
