### ISSUE TITLE
Sky drawing problem

### ISSUE THREAD

**Issue by arehberg** [Facepunch/rust-issues#45]
Seeing this on dev and in the unity editor on OSX right now

![screen shot 2015-03-16 at 12 03 09 pm](https://cloud.githubusercontent.com/assets/1221545/6674219/8c86e8b8-cbd5-11e4-9ea9-ae68424a42e8.png)

**Comment by garrynewman** [comment]
Any idea on this andre? Getting quite a few reports about it.

![image](https://cloud.githubusercontent.com/assets/928843/6764770/4b18979a-cfb9-11e4-831c-f2c2c37d07d3.png)

**Comment by andererandre** [comment]
@arehberg Can you confirm that this is fixed on dev?

**Comment by arehberg** [comment]
Seems to be fixed :)
