### ISSUE TITLE
Clients dropping without warning

### ISSUE THREAD

**Issue by thatguyyoulove** [Facepunch/rust-issues#51]
Several clients started having persistent client crashes after the Mar. 13th update. Clients usually drop within first 10 minutes of play. Server logs show client as leaving with error:

**k_EAuthSessionResponseAuthTicketCanceled**

Steamworks.NET error. Steam client auth timeouts may be the cause, but such errors do not appear in other games.

* Verifying local content checks out.
* Uninstall/Re-install doesn't fix issue.
* Restarting steam doesn't fix issue.

This has been an occasional issue for players for a few months now, judging by Google search results.

Possibly an issue within EAC?

**Comment by garrynewman** [comment]
This isn't anything new, it's Steam.
