### ISSUE TITLE
UVs are wrong on head LODs

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/rust-issues#52]
We forgot to update the UVs on the head LODs

**Comment by garrynewman** [comment]
Any progress on this Tom?

**Comment by trwb** [comment]
working on it as i type!

**Comment by garrynewman** [comment]
:+1:

**Comment by trwb** [comment]
Udpated the head and torso lod uvs. Seems like plastic Gluon doesn't like to update slack or twitter.

**Comment by garrynewman** [comment]
You can close these issues yourself when they're done :)
