### ISSUE TITLE
Building Stability Broken

### ISSUE THREAD

**Issue by Helkus** [Facepunch/rust-issues#59]
![broken1](https://cloud.githubusercontent.com/assets/4874057/6860605/9d97f6e6-d400-11e4-8b74-5b526c90887d.jpg)
![broken2](https://cloud.githubusercontent.com/assets/4874057/6860613/ad944b76-d400-11e4-86bb-ff9aa0dc93b3.jpg)

Unsure if they are not being sent to a client or actually do not exist, there is no collision or anything like that so its not an LOD problem

**Comment by garrynewman** [comment]
My theory is that the stability queue is getting that long that it's taking a long time to process. This checks out on our servers - so doing some optimizations and letting it off its leash a bit to see if it improves things.

**Comment by garrynewman** [comment]
It seems that something is breaking down the longer the server is online, as it works for a few hours and then fails. I'm doing more investigation.
