### ISSUE TITLE
Icons for barricades

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/rust-issues#84]
3 barricades for now:

![image](https://cloud.githubusercontent.com/assets/928843/7084997/4fffd4ba-df6a-11e4-829b-0143e8b24510.png)

![image](https://cloud.githubusercontent.com/assets/928843/7084998/53187bf2-df6a-11e4-9092-ce948a857492.png)

![image](https://cloud.githubusercontent.com/assets/928843/7084999/55e9735e-df6a-11e4-804a-99c3fd8cddf9.png)

**Comment by Megan-T** [comment]
![barricade_metal_wire](https://cloud.githubusercontent.com/assets/11884607/7090644/70a96564-df9c-11e4-85b7-b675fd877e11.png)
![barricade_wooden](https://cloud.githubusercontent.com/assets/11884607/7090645/70ac18c2-df9c-11e4-98c6-95a6c0f304d0.png)
![barricade_wooden_wire](https://cloud.githubusercontent.com/assets/11884607/7090646/70ac5742-df9c-11e4-997b-e835a4bb86ff.png)
