### ISSUE TITLE
Icon for camera

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/rust-issues#85]
The camera should look something like this once we have a model

![image](https://cloud.githubusercontent.com/assets/928843/7085034/91e25038-df6a-11e4-8735-8c8f13bbc6dd.png)

**Comment by Megan-T** [comment]
![camera](https://cloud.githubusercontent.com/assets/11884607/7090638/5fc5b6a8-df9c-11e4-90a7-d782bf4e67f2.png)
